### PR TITLE
Upgrade to Vapor 4

### PR DESCRIPTION
**Pull request by alexsteinerde**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Hi @alexsteinerde, is there anything that blocks merging this PR?

**Comment by MaxDesiatov** [comment]
@alexsteinerde Thanks! Do you plan to tag a release any time soon with this change included?

**Comment by alexsteinerde** [comment]
Yes! I also want to change some points in the Readme as well before tagging. I hope I can do this today and tag it tonight (UTC+1).

**Comment by MaxDesiatov** [comment]
No rush, thanks for your hard work!

**Pull request merged**
